sudo: required
before_install:
 - sudo apt-get update -qyy
 - sudo apt-get install -qyy curl bc make git build-essential #u-boot-tools
 - wget http://security.ubuntu.com/ubuntu/pool/main/u/u-boot/u-boot-tools_2016.01+dfsg1-2ubuntu3_amd64.deb -O uboot.deb
 - sudo dpkg -i uboot.deb
 - git clone https://github.com/aapav01/aarch64-linux-android-4.9-linaro /opt/toolchains/aarch64-linux-android-4.9-linaro
before_script:
 - export DEFCONFIG=akuhak_pxa1908-xcover3ltexx_defconfig
script:
# export your own config for example
 - make $DEFCONFIG
 - make -j5 --silent
 - mkimage -A arm64 -O linux -T kernel -C gzip -a 01000000 -e 01000000 -d arch/arm64/boot/Image.gz -n "pxa1928dkb linux" arch/arm64/boot/uImage
 - ./pxa1908-dtbTool -o prebuilt/dtb.img -p scripts/dtc/ arch/arm64/boot/dts/ -v
 - ./pxa-mkbootimg --kernel arch/arm64/boot/uImage --ramdisk prebuilt/ramdisk_gz --dt prebuilt/dtb.img --unknown 0x03000000 -o boot.img
 - echo "SEANDROIDENFORCE" >> boot.img
 - tar -H ustar -c boot.img
 - md5sum -t boot.img.tar >> boot.img.tar
 - mv boot.img.tar boot.tar.md5
after_script:
 - curl --upload-file boot.tar.md5 https://transfer.sh/boot.tar.md5 | grep transfer

